#!/usr/bin/env bash
# Detects supported Ajazz / Mirabox N3-family decks on USB and installs matching udev rules.
#
#   scripts/install-udev.sh            detect connected decks, install rules for them
#   scripts/install-udev.sh --all      install rules for every known supported ID (deck not plugged in)
#   scripts/install-udev.sh --dry-run  print the rules, change nothing
#
# Reads /sys directly, so it needs no lsusb. Set SYSFS_USB to point somewhere else (used by the tests).
# Note: --all also opens access for IDs that may be reused by unrelated products. Prefer detection.
set -euo pipefail
export LC_ALL=C

[ "${BASH_VERSINFO[0]}" -ge 4 ] || { echo "bash 4 or newer is required." >&2; exit 1; }

SYSFS_USB="${SYSFS_USB:-/sys/bus/usb/devices}"
# Fixed on purpose: the destination is never taken from the environment, because it is passed to sudo.
RULES_FILE=/etc/udev/rules.d/40-ajazz-deck.rules
SUDO=sudo; [ "$(id -u)" -eq 0 ] && SUDO=

# vid:pid pairs supported by the opendeck-akp03 plugin (https://github.com/4ndv/opendeck-akp03).
KNOWN=(
  0300:1001 0300:1002 0300:1003 0300:3002 0300:3003
  0b00:1001 1500:3001 6602:1000 6602:1002 6603:1002 6603:1003 5548:1001 0200:2000
)
declare -A NAMES=(
  [0300:1001]="Ajazz AKP03" [0300:1002]="Ajazz AKP03E" [0300:1003]="Ajazz AKP03R"
  [0300:3002]="Ajazz AKP03E rev. 2" [0300:3003]="Ajazz AKP03R rev. 2"
  [0b00:1001]="Mars Gaming MSD-TWO" [1500:3001]="Soomfon Stream Controller SE"
  [6602:1000]="Mirabox N3" [6602:1002]="Mirabox N3" [6603:1002]="Mirabox N3" [6603:1003]="Mirabox N3"
  [5548:1001]="TreasLin N3" [0200:2000]="Redragon Skyrider SS-551"
)

mode=detect; dry=0
for a in "$@"; do
  case "$a" in
    --all) mode=all ;;
    --dry-run) dry=1 ;;
    -h|--help) sed -n '2,9p' "$0"; exit 0 ;;
    *) echo "unknown option: $a" >&2; exit 2 ;;
  esac
done

is_known() { local k; for k in "${KNOWN[@]}"; do [ "$k" = "$1" ] && return 0; done; return 1; }

found=(); warned=" "
if [ "$mode" = all ]; then
  found=("${KNOWN[@]}")
else
  # Only accept strict 4-digit hex, so nothing odd from sysfs can end up in a rules file.
  for d in "$SYSFS_USB"/*/; do
    [ -r "$d/idVendor" ] && [ -r "$d/idProduct" ] || continue
    v="$(tr 'A-F' 'a-f' < "$d/idVendor" | head -c 8)"; p="$(tr 'A-F' 'a-f' < "$d/idProduct" | head -c 8)"
    [[ "$v" =~ ^[0-9a-f]{4}$ && "$p" =~ ^[0-9a-f]{4}$ ]] || continue
    if is_known "$v:$p"; then
      [[ " ${found[*]:-} " == *" $v:$p "* ]] || found+=("$v:$p")
    elif [ "$v" = "0300" ]; then
      if [[ "$warned" != *" $p "* ]]; then
        warned+="$p "
        echo "Note: found 0300:$p (vendor 0300, same as Ajazz decks) but it is not on the supported list." >&2
        echo "      If this is your deck, open an issue with this ID and your model name." >&2
      fi
    fi
  done
fi

if [ "${#found[@]}" -eq 0 ]; then
  echo "No supported deck detected." >&2
  echo "Plug it in with a data cable and rerun, or use --all to install rules for every supported model." >&2
  exit 1
fi

rules="# Generated by scripts/install-udev.sh. Grants the logged-in user access to the deck only.
"
for id in "${found[@]}"; do
  v="${id%:*}"; p="${id#*:}"
  echo "Found ${NAMES[$id]:-unknown} ($id)"
  rules+="SUBSYSTEM==\"usb\", ENV{DEVTYPE}==\"usb_device\", ATTR{idVendor}==\"$v\", ATTR{idProduct}==\"$p\", MODE=\"0660\", TAG+=\"uaccess\"
SUBSYSTEM==\"hidraw\", ATTRS{idVendor}==\"$v\", ATTRS{idProduct}==\"$p\", MODE=\"0660\", TAG+=\"uaccess\"
"
done

if [ "$dry" = 1 ]; then printf '\n%s' "$rules"; exit 0; fi

# No temp file: writing through sudo tee leaves no window for another process to swap the content.
printf '%s' "$rules" | $SUDO tee -- "$RULES_FILE" >/dev/null
$SUDO chmod 0644 -- "$RULES_FILE"
$SUDO udevadm control --reload-rules
for id in "${found[@]}"; do
  $SUDO udevadm trigger --subsystem-match=usb --subsystem-match=hidraw --attr-match=idVendor="${id%:*}" --attr-match=idProduct="${id#*:}"
done
echo "Installed $RULES_FILE. Unplug and replug the deck, then restart OpenDeck."
